[tool.black]
line-length = 100
target-version = ['py38']
extend-exclude = '''
^/.venv
'''
[tool.isort]
profile = "black"
skip = [".local", ".venv"]

[tool.mypy]
follow_imports = "silent"
exclude = ".venv"
disallow_untyped_defs = true
no_implicit_optional = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = false
warn_unused_configs = true
show_error_codes = true
allow_redefinition = true
warn_return_any = false
disable_error_code = ["import-untyped"]

[[tool.mypy.overrides]]
module = [
    "tasks",
    "tests.*",
]
ignore_errors = true
