# flake8: noqa

"""
This list is directly copied from https://sec-api.io/list-of-sec-filing-types
while some types are missing descriptions. Later we need to use GPT to generate a more verbose
description than these one-liners.
"""

SUPPORTED_TYPE_MAPPING = {
    "1": "National Securities Exchange Registration Application",
    "1-A": "Offering Statement 1-A, Offering Statement [Regulation A], 1A, A-1",
    "1-A POS": "Form 1-A Amendment, Post-effective amendment to Form 1-A filing",
    "1-A-W": "Withdrawl of Form 1-A, Statement of withdrawl of a Form 1-A filing",
    "1-E": "Notification under Regulation E by small business investment companies and business development companies",
    "1-E AD": "Sales material filed pursuant to Rule 607 under Regulation E.",
    "1-K": "Annual Report, Annual Report Persuant to Regulation A of the Securites Act of 1933",
    "1-SA": "Semiannual report",
    "1-U": "Current report",
    "1-Z": "Exit report",
    "1-Z-W": "Withdrawl of Form 1-Z, Statement of withdrawl of a Form 1-Z filing",
    "10-12B": "Initial general form for registration of a class of securities pursuant to section 12(b)",
    "10-12G": "Initial general form for registration of a class of securities pursuant to section 12(g)",
    "10-C": "Securities Issuer Report",
    "10-D": "Asset-Backed Issuer Distribution",
    "10-K": "Annual Report",
    "10-K/A": "Amended Annual Report",
    "10-K405": "Annual Report S-K Item 405",
    "10-K405/A": "Amended Annual Report (Regulation S-K, item 405)",
    "10-KSB": "Annual Report",
    "10-KSB/A": "Amended Annual Report",
    "10-KT": "Transition report pursuant to Rule 13a-10 or 15d-10",
    "10-KT/A": "Amended Transition report pursuant to Rule 13a-10 or 15d-10",
    "10-Q": "Quarterly Report",
    "10-Q/A": "Amended Quarterly Report",
    "10-QSB": 'Quarterly Report for Small Business, Form 10QSB is an alternative name for <a href="/Form/10QSB">Form 10QSB</a>',
    "10-QT": "Quarterly Report",
    "10-QT/A": "Amended Quarterly Report",
    "10KSB": "Annual Report",
    "10KSB/A": "Amended Annual Report",
    "10KSB40": "Annual and Transition Reports",
    "10KSB40/A": "Amended Annual and Transition Reports",
    "10KT405": "Annual Transition Report",
    "10KT405/A": "Amended Annual Transition Report",
    "10QSB": "Quarterly/Transition Report [Small Business], Optional form for quarterly and transition reports of small business issuers",
    "10QSB/A": "Amended Quarterly/Transition Report [Small Business], Optional form for quarterly and transition reports of small business issuers",
    "10SB12B": "Registration of securities for small business [Section 12(b)]",
    "10SB12G": "Registration of securities for small business [Section 12(g)]: [Amend]",
    "11-K": "Employee Stock Plan Annual Report, Annual report of employee stock purchase, savings and similar plans",
    "11-KT": "Transition report pursuant to Rule 13a-10 or 15d-10",
    "12G3-2B": "Exemptions for American Depository Receipts and Certain Foreign Securities",
    "12G32BR": "Exemptions for American Depository Receipts and Certain Foreign Securities",
    "13F-E": "Quarterly reports filed by institutional managers, Amend",
    "13F-HR": "Quarterly Report, Quarterly report filed by institutional managers, Holdings",
    "13F-NT": "Quarterly Report, 13F-NT - Quarterly report filed by institutional managers, Notice",
    "13FCONP": "Quarterly report filed by institutional managers, Holdings",
    "144": "Proposed Sale of Securities - Rule 144 Filing, NOTICE OF PROPOSED SALE OF SECURITIES PURSUANT TO RULE 144 UNDER THE SECURITIES ACT OF 1933",
    "15-12B": "Notice of termination of registration of a class of securities under Section 12(b)",
    "15-12G": "Notice of termination of registration of a class of securities under Section 12(g)",
    "15-15D": "SEC Registration Termination, Suspension of duty to report [Section 13 and 15(d)]",
    "15F-12B": "Securities registration termination of foreign private issuers [Section 12(b)]",
    "15F-12G": "Notice of termination of a foreign private issuer's registration of a class of securities under Section 12(g)",
    "15F-15D": "Notice of a foreign private issuers suspension of duty to file reports pursuant to Section 13 and 15(d) of the Act",
    "18-12B": "Registration of securities [Section 12(b)]",
    "18-K": "Annual report for foreign governments",
    "19B-4E": "Information required of an SRO Listing and Trading a New Directive Securities Product [Rule 19b-4(e)]",
    "2-A": "Registration statement for closed-end investment companies: [Amend]",
    "2-AF": "Final Report of Sales of Securities [Rule 260]",
    "2-E": "Sales material filed pursuant to Rule 609 under Regulation E.",
    "20-F": "Annual/Transition Report, Annual and transition report of foreign private issuers [Sections 13 or 15(d)]",
    "20-F/A": "Amended Annual/Transition Report, Annual and transition report of foreign private issuers [Sections 13 or 15(d)]",
    "20FR12B": "Form for initial registration of a class of securities of foreign private issuers pursuant to section 12(b)",
    "20FR12G": "Form for initial registration of a class of securities of foreign private issuers pursuant to section 12(g)",
    "24F-1": "Registration of securities by certain investment companies [Rule 24F-1]. Notification of election.",
    "24F-2EL": "Registration of securities by certain investment companies [Rule 24F-2]. Declaration of election.",
    "24F-2NT": "Annual Securities Sale Report, Annual Notice of Securities Sold",
    "24F-2TM": "Registration of securities by certain investment companies [Rule 24F-2]. Termination of Declaration of election.",
    "25": "Securities Removal Notice",
    "25-NSE": "Delisting, Notice of stock delisting from an exchange",
    "253G1": "",
    "253G2": "",
    "253G3": "",
    "253G4": "",
    "3": "Security Ownership Statement, Initial statement of beneficial ownership of securities",
    "305B2": "Application for designation of a new trustee under the Trust Indenture Act",
    "34-12H": "Application for Exemption [Section 12(g)] or from filing certain reports [Section 13(a)]",
    "35-APP": "Statement on proposed transaction where no application is prescribed [Rule 20(e)]",
    "35-CERT": "Certificate, terms and conditions [Rule 24]",
    "39-304D": "",
    "39-310B": "",
    "4": "Security Sale/Purchase Record, Statement of changes in beneficial ownership of securities",
    "40-17F1": "",
    "40-17F2": "",
    "40-17G": "Fidelity bond",
    "40-17GCS": "",
    "40-202A": "",
    "40-203A": "",
    "40-205E": "",
    "40-206A": "",
    "40-24B2": "Filing of sales literature",
    "40-33": "All stockholder derivative actions filed with a court against an investment company or an affiliate",
    "40-6B": "The Investment Company Act Excemption Application",
    "40-6C": "Application for exemption and other relief [Section 6(c)]: [Amend]",
    "40-8B25": "Document or Report",
    "40-8F-2": "Initial application for de-registration pursuant to Investment Company Act Rule 0-2",
    "40-8F-A": "Application for deregistration, abandonment of registration",
    "40-8F-B": "",
    "40-8F-L": "",
    "40-8F-M": "",
    "40-8FC": "",
    "40-APP": "Exemption Application, 40-APP - Application for exemption and other relief filed under the Investment Company Act of 1940",
    "40-F": "Annual Report / Registration, SEC Form 40-F includes Annual Reports [Section 13(a)/15(d)] or Registration Statements [Section 12]",
    "40-F/A": "Amended Annual Report / Registration, SEC Form 40-F includes Annual Reports [Section 13(a)/15(d)] or Registration Statements [Section 12]",
    "40-OIP": "Applications under the Investment Company Act reviewed by Office of Insurance Products",
    "40-RPT": "",
    "40FR12B": "Registration of a class of securities of certain Canadian issuers",
    "40FR12G": "Registration of a class of securities of certain Canadian issuers pursuant to Section 12(g) of the 1934 Act",
    "424A": "Prospectus [Rule 424(a)]",
    "424B1": "Prospectus [Rule 424(b)(1)]",
    "424B2": "Prospectus [Rule 424(b)(2)]",
    "424B3": "Prospectus [Rule 424(b)(3)]",
    "424B4": "Prospectus [Rule 424(b)(4)]",
    "424B5": "Prospectus [Rule 424(b)(5)]",
    "424B7": "Prospectus [Rule 424(b)(7)]",
    "424B8": "Prospectus [Rule 424(b)(8)]",
    "424H": "Asset Backed Notes Registration Statement, FILED PURSUANT TO RULE 424(h)",
    "425": "Merger Prospectus/Communication, Prospectuses and communications, business combinations",
    "485A24E": "Post Effective Amendments",
    "485A24F": "",
    "485APOS": "Post-effective amendment",
    "485B24E": "",
    "485B24F": "",
    "485BPOS": "Securities Registration Amendment N-1A, Post-effective amendment [Rule 485(b)]",
    "485BXT": "Post-effective amendment",
    "485BXTF": "",
    "486A24E": "",
    "486APOS": "",
    "486B24E": "",
    "486BPOS": "Post-effective amendment",
    "486BXT": "",
    "487": "Pre-effective pricing amendment",
    "497": "Investment Prospectus, Prospectus",
    "497AD": "Advertising Disclosure",
    "497H2": "Filings made pursuant to Rule 497(h)(2)",
    "497J": "Certification of Filing, Certification of no change in definitive materials",
    "497K": "Prospectus Summary",
    "497K1": "Profiles for certain open-end management investment companies",
    "497K2": "Profiles for certain open-end management investment companies",
    "497K3A": "Profiles for certain open-end management investment companies",
    "497K3B": "Profiles for certain open-end management investment companies",
    "497VPI": "",
    "497VPU": "",
    "5": "Annual Security Ownership Report, Annual statement of changes in beneficial ownership of securities",
    "6-K": "Foreign Issuer Report, Report of foreign issuer [Rules 13a-16 and 15d-16]",
    "6-K/A": "Amended Foreign Issuer Report, Report of foreign issuer [Rules 13a-16 and 15d-16]",
    "6B NTC": "",
    "6B ORDR": "",
    "8-A12B": "Securities Registration",
    "8-A12G": "Notification that a class of securities of successor issuer is deemed to be registered",
    "8-B12B": "",
    "8-B12G": "",
    "8-K": "Current Report, Unscheduled Material Events",
    "8-K/A": "Amended Current Report, Unscheduled Material Events",
    "8-K12B": "Notification that a class of securities of successor issuer is deemed to be registered pursuant to Section 12(b)",
    "8-K12G3": "Notification that a class of securities of successor issuer is deemed to be registered pursuant to Section 12(g)",
    "8-K15D5": "Notification of assumption of duty to report by successor",
    "8-M": "8-M Filing",
    "8A12BEF": "",
    "8A12BT": "",
    "8F-2 NTC": "",
    "8F-2 ORDR": "",
    "9-M": "9-M Filing",
    "ABS-15G": "Asset-Backed Securitizer Report, Asset-backed securitizer report pursuant to Section 15G, item 2.01",
    "ABS-EE": "Asset-Backed Securities Exhibits, FORM FOR SUBMISSION OF ELECTRONIC EXHIBITS FOR ASSET-BACKED SECURITIES",
    "ADB": "",
    "ADN-MTL": "",
    "ADN-MTL Filing": "",
    "ADV": "",
    "ADV-E": "",
    "ADV-E Filing": "",
    "ADV-H-C": "",
    "ADV-H-T": "",
    "ADV-NR": "",
    "ADV-NR Filing": "",
    "ADVCO": "",
    "ADVW": "",
    "AFDB": "",
    "ANNLRPT": "Periodic Development Bank filing, submitted annually",
    "APP NTC": "",
    "APP ORDR": "",
    "APP WD": "",
    "APP WD Filing": "",
    "APP WDG": "",
    "ARS": "Annual Report",
    "ATS-N": "",
    "ATS-N-C": "",
    "ATS-N-W": "",
    "ATS-N/CA": "",
    "ATS-N/MA": "",
    "ATS-N/UA": "",
    "AW": "Application for Withdrawl, Form <b>AW</b> is a request to have the SEC withdraw a prior filing or amendment.",
    "AW WD": "Withdrawal of a request for withdrawal of an amendment to a registration statement",
    "BDCO": "",
    "BW-2": "",
    "BW-3": "",
    "C": "Offering statement",
    "C-AR": "Annual report, An annual report by the company that includes financial statements.",
    "C-AR-W": "",
    "C-TR": "Termination of reporting, If eligible, a filing by the company terminating its obligation to file annual reports.",
    "C-TR-W": "",
    "C-U": "Progress updates",
    "C-U-W": "",
    "C-W": "",
    "CANCELLATION-MA": "",
    "CB": "Certain tender offers, business combinations and rights offerings, in which the subject company is a foreign private issuer of which less than 10% of its securities are held by U.S. persons",
    "CERT": "Certification",
    "CERTAMX": "Filing CERTAMX",
    "CERTARCA": "",
    "CERTBATS": "",
    "CERTBSE": "",
    "CERTCBO": "",
    "CERTCSE": "",
    "CERTNAS": "Filing CERTNAS",
    "CERTNYS": "NYSE Listing Certification, Certification by the New York Stock Exchange for Public Listing",
    "CERTPAC": "Filing CERTPAC",
    "CERTPBS": "",
    "CFPORTAL": "",
    "CFPORTAL-W": "",
    "CORRESP": "S.E.C. Correspondence Letter, <b>CORRESP</b> documents are letters or requests filed by the SEC directed toward a company.",
    "CT ORDER": "Confidential Treatment Order.",
    "D": "Stock / Securites Offering",
    "DEF 14A": "Definitive Proxy Statement, Other definitive proxy statements",
    "DEF 14C": "Definitive information statements",
    "DEF-OC": "",
    "DEF13E3": "Schedule (definitive)",
    "DEFA14A": "Proxy Soliciting Materials, Additional definitive proxy soliciting materials and Rule 14(a)(12) material",
    "DEFA14C": "Definitive additional information statement materials including Rule 14(a)(12) material",
    "DEFC14A": "Definitive proxy statement in connection with contested solicitations",
    "DEFC14C": "Definitive information statement - contested solicitations",
    "DEFM14A": "Definitive proxy statement relating to a merger or acquisition",
    "DEFM14C": "Definitive information statement relating to merger or acquisition",
    "DEFN14A": "Definitive proxy statement filed by non management",
    "DEFR14A": "Definitive revised proxy soliciting materials",
    "DEFR14C": "Definitive revised information statement materials",
    "DEFS14A": "Proxy Statement for Special Meeting, Definitive proxy statement for special meeting",
    "DEFS14C": "Information Statement - Special Meeting (definitive)",
    "DEL AM": "Separately filed delaying amendment",
    "DFAN14A": "Proxy Soliciting Materials",
    "DFRN14A": "Revised definitive proxy statement filed by non-management",
    "DOS": "",
    "DOSLTR": "",
    "DRS": "Registration Statement [Draft]",
    "DRSLTR": "Registration Statement [Draft]",
    "DSTRBRPT": "Distribution of primary obligations Development Bank report",
    "EBRD": "",
    "EFFECT": "Notice of Effectiveness",
    "F-1": "Foreign Private Issuer Registration, Registration Statement For Certain Foreign Private Issuers",
    "F-10": "Registration statement for securities of certain Canadian issuers",
    "F-10EF": "Auto effective registration statement for securities of certain Canadian issuer under the Securities Act of 1933",
    "F-10POS": "Post-effective amendment to a F-10EF registration",
    "F-1MEF": "A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form F-1",
    "F-2": "",
    "F-3": "Registration statement for specified transactions by certain foreign private issuers",
    "F-3ASR": "Automatic shelf registration statement of securities of well-known seasoned issuers",
    "F-3D": "Registration statement for dividend or interest reinvestment plan securities of foreign private issuers",
    "F-3DPOS": "Post-Effective amendment to a F-3D registration",
    "F-3MEF": "",
    "F-4": "Merger Proposal Registration, Registration of securities, foreign private issuers, business combinations",
    "F-4 POS": "Post-effective amendment to a F-4EF registration",
    "F-4EF": "",
    "F-4MEF": "",
    "F-6": "Registration statement for American Depositary Receipts representing securities of certain foreign private issuers",
    "F-6 POS": "Post-effective amendment to a F-6EF registration",
    "F-6EF": "Auto effective registration statement for American Depositary Receipts representing securities of certain foreign private issuers",
    "F-7": "Registration statement for securities of certain Canadian issuers offered for cash upon the exercise of rights granted to existing security holders",
    "F-7 POS": "Post-effective amendment to a F-7 registration",
    "F-8": "Registration statement for securities of certain Canadian issuers to be issued in exchange offers or a business combination",
    "F-8 POS": "",
    "F-80": "Registration of securities of certain Canadian issuers to be issued in exchange offers or a business combination under the Securities Act of 1933",
    "F-80POS": "",
    "F-9": "Securities Registration, Form F-9 is a securities registration filing.",
    "F-9 POS": "",
    "F-9EF": "",
    "F-N": "Notification of the appointment of an agent for service by certain foreign institutions",
    "F-X": "Service / Processing Agent Appointment",
    "FOCUSN": "Annual Audit Report, Non-public annual audit reports filed by brokers or dealers",
    "FWP": "Free Writing Prospectus, Filing under Securities Act Rules 163/433 of free writing prospectuses",
    "G-405": "G-405 Filing",
    "G-405N": "",
    "G-FIN": "G-FIN Filing",
    "G-FINW": "",
    "IADB": "",
    "ID-NEWCIK": "",
    "IFC": "",
    "IRANNOTICE": "Exchange Act Annual Disclosure Report",
    "MA": "Municipal Advisor Registration Application, Application for Municipal Advisor Registration for Business Entities",
    "MA-A": "Annual Municipal Advisor Registration Update, APPLICATION FOR MUNICIPAL ADVISOR REGISTRATION, Annual Update",
    "MA-I": "Municipal Advisor Registration Application, Application for Municipal Advisor Registration for Natural Persons",
    "MA-W": "Municipal Advisor Withdrawl, Notice of Withdrawal from Registration as a Municipal Advisor",
    "MSD": "",
    "MSDCO": "",
    "MSDW": "",
    "MSDW Filing": "",
    "N-1": "",
    "N-14": "Registration statement for fund mergers, Disclosure document includes information about a fund merger or other similar transaction.",
    "N-14 8C": "Initial registration statement filed on Form N14 by closed-end investment company (business combinations)",
    "N-14AE": "Filing N-14AE",
    "N-14MEF": "",
    "N-18F1": "Initial notification of election pursuant to Rule 18f-1 filed on Form N-18F-1",
    "N-1A": "Registration statement (including a prospectus)",
    "N-1A EL": "",
    "N-2": "Investment Company Registration, Registration statement for closed-end investment companies",
    "N-2 POSASR": "",
    "N-23C-1": "Notice by closed-end investment companies of intention to call or redeem their own securities",
    "N-23C-2": "",
    "N-23C3A": "Notification of periodic repurchase offer Filed pursuant to Rule 23c-3(b) only",
    "N-23C3B": "Filing N-23C3B",
    "N-23C3C": "",
    "N-27D-1": "",
    "N-2ASR": "",
    "N-2MEF": "",
    "N-3": "Initial registration statement on Form N-3 for separate accounts (management investment companies)",
    "N-3 EL": "",
    "N-30B-2": "Periodic and interim reports mailed to investment company shareholders",
    "N-30D": "Shareholder Report, Annual and semi-annual reports mailed to shareholders [Rule 30d-1]",
    "N-4": "Registration statement (including a prospectus)",
    "N-4 EL": "",
    "N-5": "",
    "N-54A": "Notification of election by business development companies",
    "N-54C": "Notification of election by business development companies",
    "N-6": "Registration statement for separate accounts",
    "N-6F": "Notice of intent by business development companies to elect to be subject to Sections 55 through 65 of the 1940 Act filed on Form N-6F",
    "N-8A": "Initial notification of registration under section 8(a) filed on Form N-8A",
    "N-8B-2": "Initial registration statement for unit investment trusts",
    "N-8B-4": "",
    "N-8F": "Application for deregistration made on Form N-8F",
    "N-8F NTC": "Notice of Pending Investment Company Deregistration, Notice of Applications for Deregistration under Section 8(f) of the Investment Company Act of 1940",
    "N-8F ORDR": "Order Suspending Investment Company Registration",
    "N-CEN": "Series/Class Registration Information Annual Report",
    "N-CR": "",
    "N-CSR": "Annual/semi-annual shareholder reports",
    "N-CSRS": "Semi-Annual Certified Shareholder Report, Certified Shareholder Report, Semi-Annual",
    "N-MFP": "Monthly Schedule Of Portfolio Holdings Of Money Market Funds",
    "N-MFP1": "Monthly Money Market Portfolio Report, MONTHLY SCHEDULE OF PORTFOLIO HOLDINGS OF MONEY MARKET FUNDS",
    "N-MFP2": "Monthly Schedule of Money Market Fund Holdings, MONTHLY SCHEDULE OF PORTFOLIO HOLDINGS OF MONEY MARKET FUNDS",
    "N-PX": "Proxy Voting Annual Report, N-PX - Annual Report of proxy voting record of management investment companies",
    "N-Q": "Quarterly Holding Report, Quarterly Schedule of portfolio holdings of management investment companies",
    "N-VP": "",
    "N-VPFS": "",
    "N14AE24": "",
    "N14EL24": "",
    "NO ACT": "No Action Statement, A <b>NO ACT</b> filing is a statement or request for no action to be taken.",
    "NPORT-EX": "Portfolio of Investments",
    "NPORT-P": "Monthly Portfolio Investments Report",
    "NRSRO-CE": "",
    "NRSRO-UPD": "",
    "NSAR-A": "Semi-Annual Report, Semi-annual report for management companies",
    "NSAR-AT": "",
    "NSAR-B": "Annual Report, Annual report for management companies",
    "NSAR-BT": "Transitional annual report filed on Form NSAR",
    "NSAR-U": "Annual report for unit investment trusts",
    "NT 10-D": "",
    "NT 10-K": "Notice of Late Annual Filing",
    "NT 10-K/A": "Amended Notice of Late Annual Filing",
    "NT 10-Q": "Notice of Late Quarterly Filing",
    "NT 10-Q/A": "Amended Notice of Late Quarterly Filing",
    "NT 11-K": "Notice under Rule 12b25 of inability to timely file all or part of a form 11-K",
    "NT 15D2": "",
    "NT 20-F": "Notice under Rule 12b25 of inability to timely file all or part of an annual report of form 20-F",
    "NT N-CEN": "",
    "NT N-MFP": "",
    "NT N-MFP1": "",
    "NT N-MFP2": "",
    "NT NPORT-EX": "",
    "NT NPORT-P": "",
    "NT-NCEN": "",
    "NT-NCSR": "Notice under Exchange Act Rule 12b-25 of inability to timely file Form N-CSR (annual or semi-annual report)",
    "NT-NSAR": "Notice under Exchange Act Rule 12b-25 of inability to timely file Form N-SAR",
    "NTFNCEN": "",
    "NTFNCSR": "",
    "NTFNSAR": "",
    "NTN 10D": "",
    "NTN 10K": "Filing NTN 10K",
    "NTN 10Q": "Filing NTN 10Q",
    "NTN 11K": "",
    "NTN 20F": "Filing NTN 20F",
    "NTN15D2": "",
    "OIP NTC": "",
    "OIP ORDR": "",
    "POS 8C": "Post-effective amendment by closed-end investment companies",
    "POS AM": "Post-Effective Filing Amendment, Form POS AM includes ammendments to any type of filing which has already taken effect.",
    "POS AMC": "",
    "POS AMI": "Post-effective amendment",
    "POS EX": "Registration Statement Exhibits, POS EX - Post-effective amendment adding exhibits to registration statement [Rule 462(d)]",
    "POS462B": "Post-effective amendment to Securities Act Rule 462(b) registration statement",
    "POS462C": "Post-effective amendment to a registration statement filed under Rule 462(c)",
    "POSASR": "Post-effective amendment to an automatic shelf registration statement on Form S-3ASR or Form F-3ASR",
    "PRE 14A": "Preliminary Proxy Soliciting Materials, A preliminary DEF 14A / DEFA14A proxy soliciting material filing for SEC records or approval.",
    "PRE 14C": "Preliminary information statement not related to a contested matter or merger/acquisition",
    "PRE13E3": "Initial statement (preliminary)",
    "PREA14A": "",
    "PREA14C": "",
    "PREC14A": "Preliminary proxy statement in connection with contested solicitations",
    "PREC14C": "Preliminary information statements - contested solicitations",
    "PREM14A": "Preliminary proxy statement relating to a merger or acquisition",
    "PREM14C": "Preliminary information statements relating to merger or acquisition",
    "PREN14A": "Preliminary proxy statement filed by non-management",
    "PRER14A": "Preliminary revised proxy soliciting materials",
    "PRER14C": "Preliminary revised information statements",
    "PRES14A": "Preliminary Proxy Statement/Special Meeting",
    "PRES14C": "Information Statement - Special Meeting (preliminary)",
    "PRRN14A": "Revised preliminary proxy statement filed by non-management",
    "PX14A6G": "Shareholder Solicitation by 3rd Party, Exempt Solicitation Pursuant to rules 14a-6(g) (1) and 14a-103",
    "PX14A6N": "",
    "QRTLYRPT": "Periodic Development Bank filing, submitted quarterly",
    "QUALIF": "Notice of Qualification",
    "REG-NR": "REG-NR Filing",
    "REGDEX": "Scanned Paper Filing, A <b>REGDEX</b> is a scanned paper filing that may be any form.",
    "REVOCATION-MA": "",
    "REVOKED": "Revocation of Securities",
    "RW": "Registration Withdrawal Request",
    "RW WD": "Withdrawal of a Registration Withdrawal Request",
    "S-1": "IPO Investment Prospectus",
    "S-11": "Registration statement for securities to be issued by real estate companies",
    "S-11MEF": "A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form S 11",
    "S-1MEF": "Registration of Securities Addition, Registration adding securities to prior Form S-1 registration [Rule 462(b)]",
    "S-2": "Securities Registration Statement",
    "S-20": "",
    "S-2MEF": "",
    "S-3": "Security Offering and Investment Prospectus",
    "S-3ASR": "Securities Registration, Automatic shelf registration statement of securities of well-known seasoned issuers",
    "S-3D": "Automatically effective registration statement for securities issued pursuant to dividend or interest reinvestment plans",
    "S-3DPOS": "Post-effective amendment to a S-3D registration statement",
    "S-3MEF": "A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form S 3",
    "S-4": "Business Securities Merger/Acquisition Registration, Registration of securities, business combinations",
    "S-4 POS": "Post-effective amendment to a S-4EF registration statement",
    "S-4EF": "",
    "S-4MEF": "A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form S-4",
    "S-6": "Securities Registration Statement [Investment Trust], Registration statement for unit investment trusts",
    "S-6EL24": "",
    "S-8": "Employee Benefit Plan Security Offering, Securities to be offered to employees in employee benefit plans, post-effective amendments",
    "S-8 POS": "Employee Benefit Plan Security Offering, Securities to be offered to employees in employee benefit plans, post-effective amendments",
    "S-B": "Registration statement for securities of foreign governments and subdivisions",
    "S-BMEF": "A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form SB-1",
    "SB-1": "",
    "SB-1MEF": "",
    "SB-2": "Small Business Stock Registration, Optional form for registration of securities to be sold to the public by small business issuers",
    "SB-2MEF": "",
    "SBSE": "",
    "SBSE-A": "",
    "SBSE-BD": "",
    "SBSE-C": "",
    "SC 13D": "Acquisition Statement, General statement of acquisition of beneficial ownership",
    "SC 13E1": "",
    "SC 13E3": "Privatization Statement, Going private transaction by certain issuers",
    "SC 13E4": "",
    "SC 13G": "Ownership Acquisition Statement, Statement of acquisition of beneficial ownership by individuals",
    "SC 14D1": "",
    "SC 14D9": "Solicitation, Recommendation Statements, Solicitation, recommendation statements",
    "SC 14F1": "Majority Director Change Statement, Statement regarding change in majority of directors",
    "SC 14N": "",
    "SC TO-C": "Acquisition Statement, Notice statement of Solicitation, Acquisition, or Tender Offer",
    "SC TO-I": "Tender Offer Acquisition Statement, Tender offer statement by Issuer",
    "SC TO-T": "Tender Offer Acquisition Statement, Tender Offer Statement by Third Party",
    "SC13E4F": "Issuer tender offer statement filed pursuant to Rule 13(e)(4) by foreign issuers",
    "SC14D1F": "Third party tender offer statement filed pursuant to Rule 14d-1(b) by foreign issuers",
    "SC14D9C": "Merger Offer Communication, Written communication relating to third party tender offer",
    "SC14D9F": "",
    "SD": "Specialized Disclosure Report",
    "SDR": "APPLICATION OR AMENDMENT TO APPLICATION FOR REGISTRATION OR WITHDRAWAL FROM REGISTRATION AS SECURITY-BASED SWAP DATA REPOSITORY",
    "SE": "SE Filing",
    "SEC ACTION": "SEC STAFF ACTION",
    "SEC STAFF LETTER": "Letter from SEC Staff",
    "SF-1": "",
    "SF-3": "",
    "SL": "",
    "SP 15D2": "",
    "STOP ORDER": "",
    "SUPPL": "Voluntary supplemental material filed pursuant to Section 11(a) of the Securities Act of 1933 by foreign issuers",
    "T-3": "Trust Indenture Qualification App, Application for qualification of trust indentures",
    "T-6": "",
    "TA-1": "Application for registration as a transfer agent filed pursuant to the Securities Exchange Act of 1934",
    "TA-2": "Annual report of transfer agent activities filed pursuant to the Securities Exchange Act of 1934",
    "TA-W": "Notice of withdrawal from registration as transfer agent filed pursuant to the Securities Exchange Act of 1934",
    "TACO": "",
    "TH": "",
    "TTW": "",
    "TTW Filing": "",
    "U-1": "",
    "U-12-IA": "",
    "U-12-IB": "Public Utility Compensation Statement U-12(I)-B",
    "U-13-60": "",
    "U-13E-1": "",
    "U-33-S": "",
    "U-3A-2": "",
    "U-3A3-1": "",
    "U-57": "",
    "U-6B-2": "",
    "U-7D": "",
    "U-9C-3": "",
    "U5A": "",
    "U5B": "",
    "U5S": "",
    "UNDER": "",
    "UPLOAD": "Securities Filing Public Response",
    "WDL-REQ": "",
    "WDL-REQ Filing": "",
    "X-17A-5": "Annual Report, Annual Audited Focus Report Form X-17A-5",
}
