# Constants

MAX_THEMES_PER_COMMENTARY = 10
MAX_DEVELOPMENTS_PER_COMMENTARY = 200
MAX_TOTAL_ARTICLES_PER_COMMENTARY = 200

MAX_ARTICLES_PER_DEVELOPMENT = 10
MAX_DEVELOPMENTS_PER_TOPIC = 15
MAX_MATCHED_ARTICLES_PER_TOPIC = 50
TOP_STOCKS_IN_PORTFOLIO_NUM = 20
MAX_STOCKS_PER_COMMENTARY = 50
