from agent_service.GPT.constants import GPT4_O

# Constants

MAX_THEMES_PER_COMMENTARY = 10
MAX_DEVELOPMENTS_PER_COMMENTARY = 300
MAX_TOTAL_ARTICLES_PER_COMMENTARY = 200

MAX_ARTICLES_PER_DEVELOPMENT = 10
MAX_DEVELOPMENTS_PER_TOPIC = 15
MAX_MATCHED_ARTICLES_PER_TOPIC = 50
MAX_STOCKS_PER_COMMENTARY = 50
COMMENTARY_LLM = GPT4_O
DEFAULT_BENCHMARK_NAME = "S&P 500"
