# flake8: noqa

from agent_service.tools.LLM_analysis.prompts import CITATION_PROMPT, CITATION_REMINDER
from agent_service.utils.prompt_utils import Prompt

INITIAL_BRAINSTORM_PROMPT_STR = "You are a financial analyst reviewing a large body of text data to try to identify ideas or patterns that will satisfy the particular needs of one of your clients. You will be provided with a specific definition of the kind of things that your output ideas must be. In this initial round, your goal is to brainstorm as many distinct ideas you can come up with that satisfy the client's request and have at least some grounding in the text data provided. To be clear, everything you come up with must be based on information from at least one of the provided texts, and ideally will come from multiple distinct texts. Do not brainstorm ideas that are not based on facts in your text data, if you do this you will be fired. Your output will consist of a json list of your ideas, where each item of the list will be a dictionary with two keys. The first key is `idea` and will consist of a short phrase which uniquely identifies the idea (it must clearly be an instance of the class of thing indicated by the idea definition, this is critical!), followed by a colon and then a brief explanation of no more than 30 words. You must not go into any significant detail, this will be done in a later step. The second key is `sources`, a list of integers corresponding to the Text Numbers of the source documents which inspired the idea. `sources` must always be a list even if you have one source, and it must never be empty (you must not mention any ideas that have no source). Do not include more than 10 sources. As long as each idea is reasonable and distinct, you must include as many as you can, though it is better to include just a few excellent, well-supported ideas than to produce ideas with little or no grounding in the text data provided. Be very careful not to duplicate ideas, each of your short initial phrases must be entirely distinct! You should use whatever wording the client uses to describe what they are asking for, do not use the word 'idea' unless that is the term they use. Here is the idea definition which indicates exactly what your idea should be: {idea_definition}.\n---\nHere are the texts, also delimited by ---:\n---\n{texts}\n---\nNow you must brainstorm as many ideas as you can from the texts that satisfy the client's requirements, and include the numbers of your source document you got your ideas from. Output your ideas json now:\n"

INITIAL_BRAINSTORM_PROMPT = Prompt(INITIAL_BRAINSTORM_PROMPT_STR, "INITIAL_BRAINSTORM_PROMPT")

IDEA_CLUSTER_SYS_PROMPT_STR = "You will be given a numbered list of pairs of brainstormed ideas related to a particular finance need. The overall interest of this user to come up with a nonredundant list of {items}. Your goal is to identify ideas that are similar enough that they can be collapsed into a single idea. Since all the ideas are aimed at satisfying the above user need, that connection is NOT a commonality to say Yes, there should be some other major semantic connection. The ultimate goal is to avoid redundancy, so please be do say Yes to in any case where you think the main idea largely overlaps and can be easily combined into a single idea, even if the specific details of the two are a bit different. You should give your answer for each pair by writing the number for the pair, a space, and then either Yes or No, on one line, e.g.\n10 No\n or \n10 Yes\n. Do not include a period between the number and your Yes/No. Do not include any other information, or any explanation."

IDEA_CLUSTER_MAIN_PROMPT_STR = "Decide whether or not the following pairs of ideas are similar enough to collapse into a single idea. You must output lines consisting of the number for one of the provided pairs and either Yes or No, separated by a space. Here are the pairs of ideas:\n\n{text_pairs}"

IDEA_CLASSIFY_SYS_PROMPT_STR = "You will be given a pair of brainstormed ideas related to a particular finance need. The overall interest of this user to come up with a nonredundant list of {items}. Your goal is to identify ideas that are similar enough that they can be collapsed into a single idea. Since all the ideas are aimed at satisfying the above user need, that connection is NOT a commonality to say Yes, there should be some other major semantic connection. The ultimate goal is to avoid redundancy, so please be do say Yes to in any case where you think the two ideas strongly overlap in meaning and can be easily combined into a single idea, even if the specific details of the two are a bit different. You should give your answer for the pair by writing just Yes or No. Do not include any other information, or any explanation."

IDEA_CLASSIFY_MAIN_PROMPT_STR = "Decide whether or not the pair of ideas are similar enough to collapse into a single idea. Output either Yes or No. Here is the first idea: {instance}. Here is the second: {label}"

FINAL_IDEA_SYS_PROMPT_STR = (
    "You are a financial analyst reviewing a large body of text data to try to collect a set of specific ideas that will satisfy the particular needs of one of your clients. You have already finished the initial brainstorming round which you have farmed out to your subordinate analysts, and now your goal is to do a final write up describing and justifying the choice of one particular idea as one of the answers to the client's need. You will be provided with the brainstorming need of the client and one or more initial ideas from the brainstorming session. If you are given multiple ideas they must be collapsed into one coherent idea; the idea should include as much of the individual parts as provided while not seeming to just be a simple agglomeration of two separate ideas. If there is only one idea provided, just use directly it. Regardless, your output must be focused on the idea(s) you are given, do not talk about any other idea that might be relevant to the clients need. Your output will consist first of a 3 to 10 word title that clearly expresses the idea (the title alone must contain all major information needed to understand what the idea is, be specific!) and is indisputably an instance of the specific idea definition provided. Then, on the next line, write a text of at most 500 words which describes the idea and grounds it as in evidence from the source documents. All the source documents provided should have at least some relevance to the idea you are looking at. You should try to include at many citations in your description as you reasonably can, and you must absolutely cite every source document if there are less than 5, or at least 5 if there are more than 5. But again, the more citations, the better (as long as you can include them coherently)! Never, ever just cite a single document, and try to avoid avoid citing only documents relevant to a single company unless that company is mentioned in the need expressed by the user; diversity is very important. Note that you should generally avoid directly mentioning either the word 'idea' or making direct reference to `source documents`, or even the initial client need. Just state the idea directly and cite evidence for its relevance. Do not add any markdown to your title!\n"
    + CITATION_PROMPT
)

FINAL_IDEA_MAIN_PROMPT_STR = (
    "Do a final write-up proposing one particular idea as a good answer to a user brainstorming need. Here is the specific idea definition expressed by the user: {idea_definition}. Here is the idea or ideas from the initial brainstorming that you are focusing on here:\n---\n{initial_ideas}\n---\nHere are the source document you will pull information from and cite:\n---\n{source_documents}\n---\n"
    + CITATION_REMINDER
    + "Now write your final idea, with title, main description, and citations:\n"
)

FINAL_IDEA_SYS_PROMPT = Prompt(FINAL_IDEA_SYS_PROMPT_STR, "FINAL_IDEA_SYS_PROMPT")

FINAL_IDEA_MAIN_PROMPT = Prompt(FINAL_IDEA_MAIN_PROMPT_STR, "FINAL_IDEA_MAIN_PROMPT")

BRAINSTORM_IDEAS_DESCRIPTION = "This tool takes a description of some set of items that the client is looking for (ideas), and a list of texts to search for those ideas. Examples of kinds of `ideas` might include patterns, themes, topics, events, policies, initiatives, conditions, etc. However, this tool must never be used for 'investment ideas' i.e. if the client seems to be looking directly for a list of stocks to invest in, in such cases you must use the recommendation tool and/or one of the stock filtering or stock ranking tools. This tool should also only be used when it is clear that the client wishes to extract these ideas by brainstorming them from text data. This tool MUST be used when the client clearly want multiple ideas where they intend to do some kind of further analysis on each idea (e.g. finding stocks affected by each theme derived from a brainstorming session). The idea_description should be a noun phrase that describes the particular ideas the user is looking for, e.g. 'macroeconomic patterns'. Note that in many cases the requirements of the client are very specific, and you must include all relevant details in the idea_definition passed to this tool; the tool cannot read the client's input nor the the plan you have written, so make sure the idea description provides all information provided by the client relevent to the ideas they wish to generate. The tool will NOT have the context to understand vague idea_descriptions!  For example, if the client wants key initiatives spearheaded by Biden during his presidency, your idea_description must be something like 'President Biden's key initiatives', leaving out mention of Biden or the presidency in the idea_description would be a serious mistake,  mentioning it elsewhere in the plan is not a substitue! If the client mentions a specific number of ideas they want, you must include that integer as the max_ideas argument."
